runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /2018/
  static_files: static/2018/index.html
  upload: static/2018/index.html
- url: /2018/js
  static_dir: static/2018/js
- url: /2018/css
  static_dir: static/2018/css
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /former/
  static_files: static/former/index.html
  upload: static/former/index.html
- url: /former/js
  static_dir: static/former/js
- url: /former/css
  static_dir: static/former/css
- url: /react/
  static_files: react/index.html
  upload: react/index.html
- url: /react/static
  static_dir: react/static

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
