{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgLyricRetriever',
          'title':u'pyLyricRetriever 4.5 beta',
          'size':(626, 630),
          'statusBar':1,
          'icon':'lyric_ico.ico',

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileSave',
                   'label':u'&Save',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSep1',
                   'label':u'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                   'command':'exit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuLink',
             'label':u'&Link',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuLink_utamap',
                   'label':u'\u3046\u305f\u307e\u3063\u3077',
                   'command':'launchBrowser',
                  },
                  {'type':'MenuItem',
                   'name':'menuLink_animap',
                   'label':u'\u3042\u306b\u307e\u3063\u3077',
                   'command':'launchBrowser',
                  },
                  {'type':'MenuItem',
                   'name':'menuLink_uta_net',
                   'label':u'\u6b4c\u30cd\u30c3\u30c8',
                   'command':'launchBrowser',
                  },
                  {'type':'MenuItem',
                   'name':'menuLink_kashinavi',
                   'label':u'\u6b4c\u8a5e\u30ca\u30d3',
                   'command':'launchBrowser',
                  },
                  {'type':'MenuItem',
                   'name':'menuLink_kget',
                   'label':u'\u6b4c\u8a5eGET',
                   'command':'launchBrowser',
                  },
                  {'type':'MenuItem',
                   'name':'menuLink_yahoo',
                   'label':u'Yahoo!\u30df\u30e5\u30fc\u30b8\u30c3\u30af - \u6b4c\u8a5e',
                   'command':'launchBrowser',
                  },
                  {'type':'MenuItem',
                   'name':'menuLink_kasi_time',
                   'label':u'\u6b4c\u8a5e\u30bf\u30a4\u30e0',
                   'command':'launchBrowser',
                  },
                  {'type':'MenuItem',
                   'name':'menuLink_evesta',
                   'label':u'\u30a4\u30d9\u30b9\u30bf\u6b4c\u8a5e\u3068\u308b',
                   'command':'launchBrowser',
                  },
                  {'type':'MenuItem',
                   'name':'menuLink_animesong',
                   'label':u'\u30a2\u30cb\u30e1\u30bd\u30f3\u30b0\u306e\u6b4c\u8a5e\u306a\u3089\u3053\u3053\u306b\u304a\u307e\u304b\u305b\uff1f',
                   'command':'launchBrowser',
                  },
                  {'type':'MenuItem',
                   'name':'menuLink_utaten',
                   'label':u'\u30a6\u30bf\u30c6\u30f3 (UtaTen)',
                   'command':'launchBrowser',
                  },
                  {'type':'MenuItem',
                   'name':'menuLink_joysound',
                   'label':u'JOYSOUND.com',
                   'command':'launchBrowser',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuTest',
             'label':u'&Test',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuTest_utamap',
                   'label':u'\u3046\u305f\u307e\u3063\u3077',
                   'command':'testUrl',
                  },
                  {'type':'MenuItem',
                   'name':'menuTest_animap',
                   'label':u'\u3042\u306b\u307e\u3063\u3077',
                   'command':'testUrl',
                  },
                  {'type':'MenuItem',
                   'name':'menuTest_uta_net',
                   'label':u'\u6b4c\u30cd\u30c3\u30c8',
                   'command':'testUrl',
                  },
                  {'type':'MenuItem',
                   'name':'menuTest_kashinavi',
                   'label':u'\u6b4c\u8a5e\u30ca\u30d3',
                   'command':'testUrl',
                  },
                  {'type':'MenuItem',
                   'name':'menuTest_kget',
                   'label':u'\u6b4c\u8a5eGET',
                   'command':'testUrl',
                  },
                  {'type':'MenuItem',
                   'name':'menuTest_yahoo',
                   'label':u'Yahoo!\u30df\u30e5\u30fc\u30b8\u30c3\u30af - \u6b4c\u8a5e',
                   'command':'testUrl',
                  },
                  {'type':'MenuItem',
                   'name':'menuTest_kasi_time',
                   'label':u'\u6b4c\u8a5e\u30bf\u30a4\u30e0',
                   'command':'testUrl',
                  },
                  {'type':'MenuItem',
                   'name':'menuTest_evesta',
                   'label':u'\u30a4\u30d9\u30b9\u30bf\u6b4c\u8a5e\u3068\u308b',
                   'command':'testUrl',
                  },
                  {'type':'MenuItem',
                   'name':'menuTest_animesong',
                   'label':u'\u30a2\u30cb\u30e1\u30bd\u30f3\u30b0\u306e\u6b4c\u8a5e\u306a\u3089\u3053\u3053\u306b\u304a\u307e\u304b\u305b\uff1f',
                   'command':'testUrl',
                  },
                  {'type':'MenuItem',
                   'name':'menuTest_utaten',
                   'label':u'\u30a6\u30bf\u30c6\u30f3 (UtaTen)',
                   'command':'testUrl',
                  },
                  {'type':'MenuItem',
                   'name':'menuTest_joysound',
                   'label':u'JOYSOUND.com',
                   'command':'testUrl',
                  },
              ]
             },
         ]
     },
         'strings': {
         u'error_IOError':u'IOError: the lyric site is not available now, or the network connection has problem.',
         },

         'components': [

{'type':'TextField', 
    'name':'urlTextField', 
    'position':(50, 10), 
    'size':(455, 25), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 12}, 
    'text':u'please input the url of lyric', 
    },

{'type':'Button', 
    'name':'queryButton', 
    'position':(520, 10), 
    'size':(80, 25), 
    'default':True, 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 12}, 
    'label':u'Download', 
    },

{'type':'TextArea', 
    'name':'lyricTextArea', 
    'position':(10, 40), 
    'size':(600, 500), 
    'editable':False, 
    'font':{'faceName': u'Meiryo', 'family': 'sansSerif', 'size': 12}, 
    },

{'type':'StaticText', 
    'name':'urlText', 
    'position':(10, 10), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 12}, 
    'text':u'URL:', 
    },

] # end components
} # end background
] # end backgrounds
} }
